import * as THREE from 'three';
const rnd=(a,b)=>a+Math.random()*(b-a);
export class Lightning{
 constructor(scene,terrain,audio,onStrike){this.scene=scene;this.terrain=terrain;this.audio=audio;this.onStrike=onStrike;this.events=[];this.flash=0;this.at=new THREE.Vector3();this.material=new THREE.MeshBasicMaterial({color:new THREE.Color(12,16,25),transparent:true,depthWrite:false});this.light=new THREE.PointLight(0xbcd3ff,0,9000,1);scene.add(this.light);}
 path(start,end,amount){let points=[start.clone(),end.clone()];for(let level=0;level<5;level++){const out=[points[0]];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],mid=a.clone().lerp(b,.5);mid.x+=rnd(-1,1)*amount;mid.y+=rnd(-.4,.4)*amount;mid.z+=rnd(-1,1)*amount;out.push(mid,b);}points=out;amount*=.48;}return points;}
 tube(points,radius,group,material){const curve=new THREE.CurvePath();for(let i=1;i<points.length;i++)curve.add(new THREE.LineCurve3(points[i-1],points[i]));const geometry=new THREE.TubeGeometry(curve,points.length*2,radius,5,false),mesh=new THREE.Mesh(geometry,material);group.add(mesh);}
 strike(camera,manual=false){if(this.events.length>=4)return false;const type=manual?'ground':(Math.random()<.65?'ground':Math.random()<.55?'cloud':'intercloud');const dir=new THREE.Vector3();camera.getWorldDirection(dir);dir.y=0;dir.normalize();const side=new THREE.Vector3(-dir.z,0,dir.x);let end,ground;for(let i=0;i<20;i++){const range=rnd(manual?1200:1000,manual?4500:6500),offset=rnd(-.65,.65)*range;end=camera.position.clone().addScaledVector(dir,range).addScaledVector(side,offset);ground=this.terrain.height(end.x,end.z);if(ground!==null)break;}if(ground===null||ground===undefined)return false;end.y=type==='ground'?Math.max(0,ground)+2:rnd(2600,3900);const start=end.clone().add(new THREE.Vector3(rnd(-650,650),type==='ground'?Math.max(900,3100-end.y):rnd(200,600),rnd(-650,650)));if(type==='intercloud')start.x+=rnd(1800,3500);const points=this.path(start,end,type==='ground'?240:330),group=new THREE.Group(),material=this.material.clone();this.tube(points,type==='ground'?2.4:1.8,group,material);for(let i=0;i<10;i++){const p=points[Math.floor(rnd(4,26))],branchEnd=p.clone().add(new THREE.Vector3(rnd(-650,650),rnd(-750,-100),rnd(-650,650)));const h=this.terrain.height(branchEnd.x,branchEnd.z);branchEnd.y=Math.max(branchEnd.y,(h??0)+50);const branch=this.path(p,branchEnd,90);this.tube(branch,rnd(.4,1),group,material);if(i<3){const a=branch[15],b=a.clone().add(new THREE.Vector3(rnd(-250,250),-250,rnd(-250,250)));b.y=Math.max(b.y,(this.terrain.height(b.x,b.z)??0)+40);this.tube(this.path(a,b,40),.35,group,material);}}
 this.scene.add(group);const distance=camera.position.distanceTo(type==='ground'?end:start);this.audio.thunder(distance);this.onStrike(distance,type);this.events.push({group,material,start,end,age:0,seed:Math.random(),distance});return true;}
 update(dt){this.flash=0;for(let i=this.events.length-1;i>=0;i--){const e=this.events[i];e.age+=dt;const t=e.age;let intensity=t<.035?.25:t<.08?0:t<.13?1:t<.19?.08:t<.22?.7:t<.29?.02:t<.34?.45:Math.max(0,.3-(t-.34)*1.2);e.material.opacity=intensity;e.group.visible=intensity>.025;const light=intensity*Math.min(1.2,2500/Math.max(700,e.distance));if(light>this.flash){this.flash=light;this.at.copy(e.start).lerp(e.end,.5);this.light.position.copy(e.end).add(new THREE.Vector3(0,350,0));}if(t>.85){this.scene.remove(e.group);e.group.traverse(o=>o.geometry?.dispose());e.material.dispose();this.events.splice(i,1);}}this.light.intensity=this.flash*150000;}
 clear(){for(const e of this.events){this.scene.remove(e.group);e.group.traverse(o=>o.geometry?.dispose());e.material.dispose();}this.events=[];this.flash=0;this.light.intensity=0;}
}
