// Route-following bicycle approximation. All distances in metres, angles in radians.
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const wrapAngle=a=>Math.atan2(Math.sin(a),Math.cos(a));
export class Route {
 constructor(csv){const rows=csv.trim().split(/\r?\n/).slice(1).map(l=>l.split(',').map(Number));this.points=rows.map(r=>({x:r[1]-355000,y:r[4]-300,z:5580000-r[2]}));this.s=[0];for(let i=1;i<this.points.length;i++)this.s.push(this.s[i-1]+this.distance(i-1,i));this.length=this.s.at(-1)+this.distance(this.points.length-1,0);this.n=this.points.length;this.s3=[0];for(let i=1;i<this.n;i++){const a=this.points[i-1],b=this.points[i];this.s3.push(this.s3[i-1]+Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z));}const a=this.points.at(-1),b=this.points[0];this.length3=this.s3.at(-1)+Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z);}
 distance(a,b){const p=this.points[a],q=this.points[b];return Math.hypot(q.x-p.x,q.z-p.z);}
 sample(distance){let s=((distance%this.length)+this.length)%this.length,lo=0,hi=this.n-1;while(lo<hi){let m=(lo+hi+1)>>1;if(this.s[m]<=s)lo=m;else hi=m-1;}let i=lo,j=(i+1)%this.n,p=this.points[i],q=this.points[j],span=(j?this.s[j]:this.length)-this.s[i],t=(s-this.s[i])/span;return {x:p.x+(q.x-p.x)*t,y:p.y+(q.y-p.y)*t,z:p.z+(q.z-p.z)*t,yaw:Math.atan2(q.x-p.x,-(q.z-p.z)),grade:(q.y-p.y)/span,i};}
 distance3(s){const p=this.sample(s),i=p.i,j=(i+1)%this.n;const plan=(j?this.s[j]:this.length)-this.s[i],surface=(j?this.s3[j]:this.length3)-this.s3[i];return this.s3[i]+((((s%this.length)+this.length)%this.length)-this.s[i])/plan*surface;}
 frame(s){const p=this.sample(s),a=this.sample(s-3),b=this.sample(s+3);p.yaw=Math.atan2(b.x-a.x,-(b.z-a.z));p.curve=wrapAngle(this.sample(s+5).yaw-this.sample(s-5).yaw)/10;return p;}
}
export class Drive {
 constructor(route){this.route=route;this.s=0;this.offset=0;this.angle=0;this.v=0;this.steer=0;this.lap=1;this.time=0;this.best=null;this.lastLap=null;this.total=0;}
 reset(){this.offset=0;this.angle=0;this.v=0;this.steer=0;}
 step(dt,input){let p=this.route.frame(this.s);let off=Math.abs(this.offset)>4.9;this.steer+=(input.steer-this.steer)*(1-Math.exp(-dt*7));const throttle=clamp(input.throttle,0,1),brake=clamp(input.brake,0,1);let acceleration=throttle*(6.8/(1+this.v/45))-brake*13-.13-this.v*this.v*.0008-9.81*p.grade*Math.cos(this.angle);if(off)acceleration-=1.8+this.v*.28;this.v=clamp(this.v+acceleration*dt,0,65);let steerAngle=this.steer*(.42/(1+this.v*.065));let yawRate=clamp(this.v/2.7*Math.tan(steerAngle),-7.8/Math.max(this.v,4),7.8/Math.max(this.v,4));let ds=this.v*Math.cos(this.angle)/clamp(1-p.curve*this.offset,.4,1.6)*dt;this.angle=wrapAngle(this.angle+yawRate*dt-p.curve*ds);this.offset+=this.v*Math.sin(this.angle)*dt;if(Math.abs(this.offset)>43){this.offset=clamp(this.offset,-43,43);this.v*=Math.exp(-dt*6);}this.s+=ds;this.total+=ds;this.time+=dt;if(this.s>=this.route.length){this.s-=this.route.length;if(this.total>this.route.length*.98){this.lastLap=this.time;this.best=this.best===null?this.time:Math.min(this.best,this.time);this.time=0;this.lap++;}}if(this.s<0)this.s+=this.route.length;return off;}
 pose(){const p=this.route.frame(this.s);return {x:p.x+Math.cos(p.yaw)*this.offset,y:p.y+.06,z:p.z+Math.sin(p.yaw)*this.offset,yaw:p.yaw+this.angle,grade:p.grade};}
}
