import {setupWakeLock} from './wake-lock.js';
import {shadeLog} from './ember-material.js';
import {setupPanelUI} from './panel-ui.js';
import {t,initI18n} from './i18n.js';
import {makeRockGeometry,makeRockMaterial} from './rocks.js';
import {FireAudio} from './audio.js';
import * as T from 'three';
import * as C from 'cannon-es';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
const $=id=>document.getElementById(id),canvas=$('scene');
const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?.85:1.25));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.65;
const scene=new T.Scene();scene.background=new T.Color('#080e18');scene.fog=new T.FogExp2('#080e18',.045);
const camera=new T.PerspectiveCamera(43,innerWidth/innerHeight,.1,70);camera.position.set(5.3,3.5,7.2);const orbit=new OrbitControls(camera,canvas);orbit.target.set(.45,.9,0);orbit.enableDamping=true;orbit.minDistance=2.5;orbit.maxDistance=14;orbit.maxPolarAngle=Math.PI*.485;
scene.add(new T.HemisphereLight(0x829cc6,0x20201e,.4));const moon=new T.DirectionalLight(0x8caccf,.7);moon.position.set(-4,8,-5);scene.add(moon);
const fireLight=new T.PointLight(0xff8534,55,13,2);fireLight.position.set(0,1,0);fireLight.castShadow=true;fireLight.shadow.mapSize.set(1024,1024);fireLight.shadow.bias=-.0005;fireLight.shadow.normalBias=.025;fireLight.shadow.radius=2;fireLight.shadow.camera.near=.1;fireLight.shadow.camera.far=14;scene.add(fireLight);
const world=new C.World({gravity:new C.Vec3(0,-9.81,0)});world.broadphase=new C.SAPBroadphase(world);world.solver.iterations=14;world.defaultContactMaterial.friction=.65;world.defaultContactMaterial.restitution=.08;world.allowSleep=true;
const floor=new C.Body({mass:0,shape:new C.Plane()});floor.quaternion.setFromEuler(-Math.PI/2,0,0);world.addBody(floor);
function noiseTexture(kind){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),im=ctx.createImageData(512,512);for(let y=0;y<512;y++)for(let x=0;x<512;x++){let n=Math.random(),v=kind==='ground'?40+n*32+8*Math.sin(x*.17)*Math.sin(y*.1):50+Math.sin(x*.22+Math.sin(y*.015)*3)*15+n*35;let i=(y*512+x)*4;im.data[i]=v;im.data[i+1]=v*(kind==='ground'?.91:.68);im.data[i+2]=v*(kind==='ground'?.8:.43);im.data[i+3]=255;}ctx.putImageData(im,0,0);if(kind==='bark'){for(let i=0;i<150;i++){let x=Math.random()*512;ctx.strokeStyle=`rgba(8,5,3,${.2+Math.random()*.5})`;ctx.lineWidth=1+Math.random()*4;ctx.beginPath();ctx.moveTo(x,0);for(let y=0;y<=512;y+=16)ctx.lineTo(x+Math.sin(y*.025+i)*3,y);ctx.stroke();}}const tx=new T.CanvasTexture(c);tx.wrapS=tx.wrapT=T.RepeatWrapping;tx.colorSpace=T.SRGBColorSpace;return tx;}
const groundTex=noiseTexture('ground');groundTex.repeat.set(16,16);const ground=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({map:groundTex,roughness:1,bumpMap:groundTex,bumpScale:.045,color:0x878580}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const ash=new T.Mesh(new T.CircleGeometry(1.45,64),new T.MeshStandardMaterial({color:0x242322,roughness:1,map:groundTex}));ash.rotation.x=-Math.PI/2;ash.position.y=.008;scene.add(ash);
for(let i=0;i<18;i++){
  const a=i/18*Math.PI*2,r=1.49+(Math.random()-.5)*.08,radius=.24+Math.random()*.065;
  const g=makeRockGeometry(radius,Math.random()*100);
  const m=new T.Mesh(g,makeRockMaterial(Math.random()*100));
  m.scale.set(1.05+Math.random()*.23,.7+Math.random()*.2,.86+Math.random()*.22);m.rotation.set((Math.random()-.5)*.35,Math.random()*Math.PI*2,(Math.random()-.5)*.3);
  m.position.set(Math.cos(a)*r,0,Math.sin(a)*r);m.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(m);m.position.y=-bounds.min.y-.025;
  m.castShadow=m.receiveShadow=true;scene.add(m);world.addBody(new C.Body({mass:0,shape:new C.Sphere(radius*.95),position:new C.Vec3(m.position.x,m.position.y,m.position.z)}));
}
// Distant trunks keep the surroundings visible through the heat shimmer.
for(let i=0;i<65;i++){let a=Math.random()*Math.PI*2,r=9+Math.random()*20;const m=new T.Mesh(new T.CylinderGeometry(.12,.28,8,7),new T.MeshStandardMaterial({color:0x292a2c,roughness:1}));m.position.set(Math.cos(a)*r,4,Math.sin(a)*r);scene.add(m);}
const fireAudio=new FireAudio();
const bark=noiseTexture('bark');const logs=[];let selected=null,held=null,elapsed=0,paused=false,wind=.6,direction=45,speed=1,quenched=0,idCounter=0;
const v=new T.Vector3();const MAX=20;
function toast(key){toast.key=key;$('toast').textContent=t(key);$('toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.opacity=0,2600);}
function addLog(pos,angle=0,hot=false){if(logs.length>=MAX){toast('maxLogs');return null;}const length=1.35+Math.random()*.35,r=.14+Math.random()*.035;const g=new T.CylinderGeometry(r*.86,r,length,12,12);g.rotateZ(Math.PI/2);const pp=g.attributes.position;for(let i=0;i<pp.count;i++){let x=pp.getX(i),y=pp.getY(i),z=pp.getZ(i),s=1+.045*Math.sin(x*21+Math.atan2(z,y)*7);pp.setXYZ(i,x,y*s,z*s);}g.computeVertexNormals();const material=new T.MeshStandardMaterial({map:bark,bumpMap:bark,bumpScale:.045,roughness:.97,color:0xbba18b});const charUniform={value:hot?.12:0},heatUniform={value:hot?.5:0};shadeLog(material,charUniform,heatUniform);const mesh=new T.Mesh(g,material);mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);const body=new C.Body({mass:2.3,shape:new C.Box(new C.Vec3(length/2,r*.85,r*.85)),position:new C.Vec3(...pos),linearDamping:.2,angularDamping:.4,sleepSpeedLimit:.05,sleepTimeLimit:1});body.quaternion.setFromEuler(0,angle,.03);body.isFirewood=true;body.addEventListener('collide',event=>{if(!paused)fireAudio.impact(body,event);});world.addBody(body);const log={id:++idCounter,mesh,body,length,r,temp:hot?610:20,fuel:1,char:hot?.12:0,burn:hot?.8:0,charUniform,heatUniform,ashTime:0};logs.push(log);syncLog(log);return log;}
function syncLog(l){l.mesh.position.copy(l.body.position);l.mesh.quaternion.copy(l.body.quaternion);}
function reset(){fireAudio.reset();release();dragging=false;logs.forEach(l=>{world.removeBody(l.body);scene.remove(l.mesh);l.mesh.geometry.dispose();l.mesh.material.dispose();});logs.length=0;selected=null;elapsed=0;quenched=0;idCounter=0;paused=false;$('pause').textContent=t('pause');particleEpoch++;for(let i=0;i<N;i++){particleData[i*12+3]=-1;}sourceData.fill(0);if(gpu)gpu.device.queue.writeBuffer(gpu.buffer,0,particleData);syncParticles();updateUI();}
function select(l){selected=l;updateUI();}
function hold(l){if(held&&held!==l)release();held=l;l.body.type=C.Body.KINEMATIC;l.body.mass=0;l.body.updateMassProperties();l.body.velocity.setZero();l.body.angularVelocity.setZero();l.body.wakeUp();select(l);}
function release(){if(held){held.body.type=C.Body.DYNAMIC;held.body.mass=2.3;held.body.updateMassProperties();held.body.wakeUp();held=null;}orbit.enabled=true;}
function rotate(amount,tilt=false){if(!selected)return toast('selectFirst');hold(selected);const q=new C.Quaternion();q.setFromAxisAngle(new C.Vec3(tilt?1:0,tilt?0:1,0),amount);q.mult(held.body.quaternion,held.body.quaternion);syncLog(held);}
function raise(amount){if(!selected)return toast('selectFirst');hold(selected);held.body.position.y=Math.max(.2,Math.min(3.5,held.body.position.y+amount));syncLog(held);}
// Raymarched flame volume, attached to each burning log segment.
const emitA=Array.from({length:MAX},()=>new T.Vector4()),emitB=Array.from({length:MAX},()=>new T.Vector4());
const depthTarget=new T.WebGLRenderTarget(innerWidth,innerHeight);depthTarget.depthTexture=new T.DepthTexture(innerWidth,innerHeight);const inverseVP=new T.Matrix4();
// Only depth is needed here: avoid shading the rocks/logs and drawing six shadow faces twice.
const depthMaterial=new T.MeshDepthMaterial();depthMaterial.colorWrite=false;
const fireUniforms={sceneDepth:{value:depthTarget.depthTexture},inverseVP:{value:inverseVP},resolution:{value:new T.Vector2(innerWidth*renderer.getPixelRatio(),innerHeight*renderer.getPixelRatio())},time:{value:0},eye:{value:camera.position},emitA:{value:emitA},emitB:{value:emitB},windV:{value:new T.Vector2()},amount:{value:1}};
const noiseGLSL=`float hash(vec3 p){p=fract(p*.3183099+vec3(.1,.2,.3));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 p){return noise(p)*.57+noise(p*2.03)*.28+noise(p*4.07)*.15;}`;
const marchSteps=innerWidth<700?32:48;
const flameMat=new T.ShaderMaterial({transparent:true,depthWrite:false,depthTest:false,side:T.BackSide,blending:T.AdditiveBlending,uniforms:fireUniforms,vertexShader:`varying vec3 wpos;void main(){wpos=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(wpos,1.);}`,fragmentShader:`precision highp float; varying vec3 wpos;uniform vec3 eye;uniform float time;uniform float amount;uniform vec4 emitA[20];uniform vec4 emitB[20];uniform vec2 windV;uniform sampler2D sceneDepth;uniform mat4 inverseVP;uniform vec2 resolution;${noiseGLSL}
void main(){vec3 rd=normalize(wpos-eye);vec3 inv=1./rd;vec3 t0=(vec3(-4.,.05,-4.)-eye)*inv;vec3 t1=(vec3(4.,4.6,4.)-eye)*inv;vec3 lo=min(t0,t1),hi=max(t0,t1);float start=max(max(lo.x,lo.y),lo.z),end=min(min(hi.x,hi.y),hi.z);start=max(start,0.);vec2 screenUV=gl_FragCoord.xy/resolution;float depth=texture2D(sceneDepth,screenUV).x;vec4 worldDepth=inverseVP*vec4(screenUV*2.-1.,depth*2.-1.,1.);worldDepth/=worldDepth.w;end=min(end,dot(worldDepth.xyz-eye,rd));if(end<start)discard;float stepSize=(end-start)/${marchSteps}.;vec3 col=vec3(0);float alpha=0.;float jitter=hash(vec3(gl_FragCoord.xy,time))*.8;for(int j=0;j<${marchSteps};j++){vec3 p=eye+rd*(start+(float(j)+jitter)*stepSize);float field=0.;float maxHeat=0.;for(int i=0;i<20;i++){float b=emitA[i].w;if(b<.02)continue;float h=p.y-(emitA[i].y+emitB[i].y)*.5;if(h<-.12||h>2.6)continue;vec3 pp=p;pp.xz-=windV*h*h*.16;vec3 ab=emitB[i].xyz-emitA[i].xyz;float t=clamp(dot(pp-emitA[i].xyz,ab)/max(dot(ab,ab),.001),0.,1.);vec3 nearP=mix(emitA[i].xyz,emitB[i].xyz,t);float radius=.22+.22*b;float d=length(pp.xz-nearP.xz);float taper=max(0.,1.-max(h,0.)/(.45+1.65*b));float f=max(0.,1.-d/(radius*taper+.025))*taper*b;field=max(field,f);maxHeat=max(maxHeat,b);}if(field>.001){vec3 np=p*vec3(3.8,2.7,3.8)-vec3(windV.x*time*.4,time*2.8,windV.y*time*.4);float n=fbm(np+vec3(noise(np*.7+time)*1.4));float density=max(0.,field-(n*.68+.1))*3.2;float core=clamp(density*1.7,0.,1.);vec3 c=mix(vec3(1.65,.055,.002),vec3(3.2,.72,.025),smoothstep(.03,.65,core));c=mix(c,vec3(3.8,2.9,1.15),pow(core,5.));float a=1.-exp(-density*stepSize*5.);col+=(1.-alpha)*c*a;alpha+=(1.-alpha)*a;if(alpha>.98)break;}}gl_FragColor=vec4(col*amount,alpha);}`});
const flame=new T.Mesh(new T.BoxGeometry(8,4.55,8),flameMat);flame.position.y=2.325;flame.renderOrder=3;scene.add(flame);
// Unified smoke and spark simulation: WebGPU compute, CPU fallback.
const N=3072,particleData=new Float32Array(N*12);for(let i=0;i<N;i++){particleData[i*12+3]=-1;particleData[i*12+7]=i%9===0?1:0;particleData[i*12+8]=Math.random();}
let gpu=null,gpuBusy=false,particleEpoch=0;const smokeGeo=new T.BufferGeometry(),positions=new Float32Array(N*3),ages=new Float32Array(N),types=new Float32Array(N),seeds=new Float32Array(N);smokeGeo.setAttribute('position',new T.BufferAttribute(positions,3));smokeGeo.setAttribute('age',new T.BufferAttribute(ages,1));smokeGeo.setAttribute('kind',new T.BufferAttribute(types,1));smokeGeo.setAttribute('seed',new T.BufferAttribute(seeds,1));
const smokeMat=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{pixelRatio:{value:renderer.getPixelRatio()},firePower:{value:1}},vertexShader:`attribute float age;attribute float kind;attribute float seed;uniform float pixelRatio;varying float a;varying float k;varying float s;void main(){a=age;k=kind;s=seed;vec4 mv=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*mv;float size=kind>.5?.025:(.18+max(age,0.)*.18);gl_PointSize=clamp(size*560.*pixelRatio/-mv.z,1.,200.);if(age<0.)gl_PointSize=0.;}`,fragmentShader:`precision highp float;varying float a;varying float k;varying float s;uniform float firePower;void main(){if(a<0.)discard;vec2 p=gl_PointCoord*2.-1.;float r=dot(p,p);if(r>1.)discard;if(k>.5){float b=pow(1.-r,3.)*max(0.,1.-a/3.);gl_FragColor=vec4(4.,.9,.08,b*.9);}else{float n=.8+.2*sin(p.x*12.+s*80.)*sin(p.y*9.+s*30.);float alpha=pow(1.-r,2.)*smoothstep(0.,.6,a)*max(0.,1.-a/7.)*.07*n;vec3 color=mix(vec3(.21,.18,.16),vec3(.15,.17,.20),clamp(a*.6,0.,1.));color+=vec3(.24,.075,.015)*exp(-a*2.)*firePower;gl_FragColor=vec4(color,alpha);}}`});const particles=new T.Points(smokeGeo,smokeMat);particles.frustumCulled=false;particles.renderOrder=4;scene.add(particles);
const wgsl=`struct Particle{pos:vec4f,vel:vec4f,extra:vec4f};struct Params{dt:f32,time:f32,wx:f32,wz:f32};struct Source{a:vec4f,b:vec4f};@group(0) @binding(0)var<storage,read_write> particles:array<Particle>;@group(0) @binding(1)var<uniform> params:Params;@group(0) @binding(2)var<storage,read> sources:array<Source>;fn hash(n:f32)->f32{return fract(sin(n*127.1+311.7)*43758.5453);}@compute @workgroup_size(64)fn main(@builtin(global_invocation_id) gid:vec3u){let i=gid.x;if(i>=3072u){return;}var p=particles[i];let dt=params.dt;let seed=p.extra.x;let spark=p.vel.w>.5;let life=select(7.,3.,spark);if(p.pos.w<0.||p.pos.w>life||p.pos.y<0.){let idx=(i+u32(params.time*3.))%20u;let src=sources[idx];let sourceHeat=src.a.w;let chance=hash(f32(i)+floor(params.time*30.));if(sourceHeat>.03&&chance<sourceHeat*.7){let along=hash(f32(i)*3.1+params.time);p.pos=vec4f(mix(src.a.xyz,src.b.xyz,along)+vec3f((seed-.5)*.2,.12,(hash(seed*100.)-.5)*.2),0.);p.vel=vec4f((seed-.5)*.2,select(.5,1.8,spark)+sourceHeat,(hash(seed*70.)-.5)*.2,p.vel.w);p.extra.y=sourceHeat;}else{p.pos.w=-1.;} }else{let t=params.time;let q=p.pos.xyz;let turbulence=vec3f(sin(q.y*3.2+t*1.7+seed*6.)+cos(q.z*2.3-t),sin(q.x*4.+t),cos(q.y*2.8-t*1.2+seed*8.)-sin(q.x*3.+t));let buoyancy=select(.9*exp(-p.pos.w*.4)*p.extra.y,-.9,spark);p.vel=vec4f(p.vel.xyz+(vec3f(params.wx*.5,buoyancy,params.wz*.5)+turbulence*select(.65,.4,spark)-p.vel.xyz*.38)*dt,p.vel.w);p.pos=vec4f(p.pos.xyz+p.vel.xyz*dt,p.pos.w+dt);}particles[i]=p;}`;
async function initGPU(){try{if(!navigator.gpu)throw Error('unavailable');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('adapter');const device=await adapter.requestDevice();const module=device.createShaderModule({code:wgsl});const info=module.getCompilationInfo?await module.getCompilationInfo():{messages:[]};if(info.messages.some(m=>m.type==='error'))throw Error(info.messages.map(m=>m.message).join('\n'));const buffer=device.createBuffer({size:particleData.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(buffer,0,particleData);const uniform=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});const sources=device.createBuffer({size:MAX*32,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});const read=device.createBuffer({size:particleData.byteLength,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const pipeline=await device.createComputePipelineAsync({layout:'auto',compute:{module,entryPoint:'main'}});const bind=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer}},{binding:1,resource:{buffer:uniform}},{binding:2,resource:{buffer:sources}}]});gpu={device,buffer,uniform,sources,read,pipeline,bind};device.lost.then(()=>{gpu=null;$('engine').textContent=t('cpu');toast('gpuLost');});$('engine').textContent=t('gpu');}catch(e){console.warn('Compute fallback:',e);$('engine').title=String(e.message||e);$('engine').textContent=t('cpu');toast('gpuFallback');}}
const sourceData=new Float32Array(MAX*8);let gpuAccum=0;
// Particle kind and seed never change; upload these attributes only once.
for(let i=0;i<N;i++){types[i]=particleData[i*12+7];seeds[i]=particleData[i*12+8];}
smokeGeo.attributes.position.setUsage(T.DynamicDrawUsage);smokeGeo.attributes.age.setUsage(T.DynamicDrawUsage);
function syncParticles(){for(let i=0;i<N;i++){const o=i*12,j=i*3;positions[j]=particleData[o];positions[j+1]=particleData[o+1];positions[j+2]=particleData[o+2];ages[i]=particleData[o+3];}smokeGeo.attributes.position.needsUpdate=true;smokeGeo.attributes.age.needsUpdate=true;}

function updateParticles(dt){if(gpu){gpuAccum+=dt;if(gpuBusy)return;gpuBusy=true;const g=gpu,epoch=particleEpoch;g.device.queue.writeBuffer(g.uniform,0,new Float32Array([Math.min(gpuAccum,1.),elapsed,fireUniforms.windV.value.x,fireUniforms.windV.value.y]));gpuAccum=0;g.device.queue.writeBuffer(g.sources,0,sourceData);const enc=g.device.createCommandEncoder(),pass=enc.beginComputePass();pass.setPipeline(g.pipeline);pass.setBindGroup(0,g.bind);pass.dispatchWorkgroups(N/64);pass.end();enc.copyBufferToBuffer(g.buffer,0,g.read,0,particleData.byteLength);g.device.queue.submit([enc.finish()]);g.read.mapAsync(GPUMapMode.READ).then(()=>{if(epoch===particleEpoch)particleData.set(new Float32Array(g.read.getMappedRange()));g.read.unmap();syncParticles();}).catch(e=>{console.warn(e);gpu=null;$('engine').textContent=t('cpu');}).finally(()=>gpuBusy=false);}else{for(let i=0;i<N;i++){let o=i*12,a=particleData[o+3],spark=particleData[o+7]>.5,s=particleData[o+8];if(a<0||a>(spark?3:7)||particleData[o+1]<0){let idx=(i+Math.floor(elapsed*3))%MAX,b=sourceData[idx*8+3];if(b>.03&&Math.random()<b*.2){let t=Math.random();for(let k=0;k<3;k++)particleData[o+k]=T.MathUtils.lerp(sourceData[idx*8+k],sourceData[idx*8+4+k],t);particleData[o+1]+=.12;particleData[o+3]=0;particleData[o+4]=(s-.5)*.2;particleData[o+5]=(spark?1.8:.5)+b;particleData[o+6]=(Math.random()-.5)*.2;particleData[o+9]=b;}else particleData[o+3]=-1;}else{let y=particleData[o+1];particleData[o+4]+=(fireUniforms.windV.value.x*.5+Math.sin(y*3+elapsed+s*6)*.65-particleData[o+4]*.38)*dt;particleData[o+5]+=((spark?-.9:.9*Math.exp(-a*.4)*particleData[o+9])-particleData[o+5]*.38)*dt;particleData[o+6]+=(fireUniforms.windV.value.y*.5+Math.cos(y*3-elapsed+s*8)*.65-particleData[o+6]*.38)*dt;for(let k=0;k<3;k++)particleData[o+k]+=particleData[o+4+k]*dt;particleData[o+3]+=dt;}}syncParticles();}}
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloomPass=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.3,.65,1.05);composer.addPass(bloomPass);
const shimmer=new ShaderPass({uniforms:{tDiffuse:{value:null},time:{value:0},center:{value:new T.Vector2(.5,.5)},strength:{value:0},aspect:{value:innerWidth/innerHeight}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D tDiffuse;uniform float time,strength,aspect;uniform vec2 center;varying vec2 vUv;void main(){vec2 p=vUv-center;float mask=exp(-p.x*p.x*aspect*aspect*90.-p.y*p.y*30.)*smoothstep(-.05,.08,p.y);vec2 shift=vec2(sin(p.y*180.-time*9.)*sin(p.x*95.+time*3.),cos(p.x*110.+time*5.))*mask*strength*.0015;gl_FragColor=texture2D(tDiffuse,vUv+shift);}`});composer.addPass(shimmer);composer.addPass(new OutputPass());
function burnStep(dt){quenched=Math.max(0,quenched-dt);for(const l of logs){let incoming=0;for(const other of logs){if(other===l)continue;const d=l.body.position.distanceTo(other.body.position);incoming+=other.burn*145/(.25+d*d);incoming+=Math.max(0,other.temp-l.temp)*.022/Math.max(.25,d*d);}const cooling=(l.temp-20)*(.035+wind*.014);const combustion=l.fuel>0&&quenched<=0?T.MathUtils.smoothstep(l.temp,240,510)*Math.min(1,l.fuel*18):0;l.burn=T.MathUtils.lerp(l.burn,combustion,Math.min(1,dt*3));l.temp=T.MathUtils.clamp(l.temp+(incoming+combustion*95-cooling-(quenched>0?280:0))*dt,20,920);if(l.fuel>0){const use=(l.burn*.0015+(l.temp>280?.00025:0))*dt;l.fuel=Math.max(0,l.fuel-use);l.char=Math.min(1,l.char+use*4.4);}else{l.burn=0;l.ashTime+=dt;}l.charUniform.value=l.char;l.heatUniform.value=T.MathUtils.smoothstep(l.temp,260,800)*(l.fuel>0?1:Math.max(0,1-l.ashTime/70));if(l.fuel<=0){l.mesh.material.color.setHex(0x969187);if(l.ashTime>90){scene.remove(l.mesh);world.removeBody(l.body);l.mesh.geometry.dispose();l.mesh.material.dispose();if(selected===l)selected=null;if(held===l)held=null;}}}for(let i=logs.length-1;i>=0;i--)if(logs[i].ashTime>90)logs.splice(i,1);}
function refreshControlLabels(){
 $('fold').setAttribute('aria-expanded',String(!$('panel').classList.contains('collapsed')));
 for(const [id,key] of [['pause',paused?'resume':'pause'],['mute',!fireAudio.available?'audioUnavailable':fireAudio.muted?'unmute':'mute'],['hide',document.body.classList.contains('zen')?'showControls':'view']]){const el=$(id);el.textContent=t(key);el.title=t(key);}
 $('fold').setAttribute('aria-label',t($('panel').classList.contains('collapsed')?'expand':'fold'));$('fold').title=$('fold').getAttribute('aria-label');
 $('engine').textContent=t(gpu?'gpu':'cpu');if(toast.key)$('toast').textContent=t(toast.key);
}
function stateName(l){return l.fuel<=0?t('ash'):l.burn>.15?t('burning'):l.temp>280?t('embers'):l.temp>90?t('heating'):l.char>.2?t('charred'):t('unlit');}
function updateUI(){refreshControlLabels();if(selected){$('selection').textContent=`${t('log')} ${selected.id} · ${stateName(selected)}${held===selected?' · '+t('held'):''}`;$('temp').textContent=Math.round(selected.temp)+' °C';$('fuel').textContent=Math.round(selected.fuel*100)+' %';$('char').textContent=Math.round(selected.char*100)+' %';}else{$('selection').textContent=t('selectPrompt');for(let id of ['temp','fuel','char'])$(id).textContent='—';}$('count').textContent=t('logCount',{count:logs.length});const n=Math.floor(elapsed);$('clock').textContent=String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');const activity=logs.reduce((s,l)=>s+l.burn,0);$('activity').textContent=!logs.length?t('empty'):paused?t('resting'):activity>2?t('strong'):activity>.2?t('gentle'):logs.some(l=>l.temp>280)?t('embersLeft'):t('out');}
function ignite(){if(!logs.length)return toast('placeFirst');quenched=0;let targets=selected?[selected]:logs.filter(l=>l.body.position.length()<1.8);for(let l of targets)if(l.fuel>0){l.temp=Math.max(l.temp,560);l.burn=.65;}toast(selected?'ignitedSelected':'ignitedFire');}
function extinguish(){quenched=7;for(let l of logs){l.burn=0;l.temp=Math.min(l.temp,210);}toast('extinguished');}
const unlockAudio=()=>{void fireAudio.unlock().then(ok=>{if(!ok){$('mute').textContent=t('audioUnavailable');$('mute').disabled=true;}});};window.addEventListener('pointerdown',unlockAudio,{passive:true});window.addEventListener('keydown',unlockAudio,{passive:true});$('volume').oninput=e=>{fireAudio.setVolume(Number(e.target.value)/100);$('volumeVal').textContent=e.target.value+'%';};$('mute').onclick=()=>{fireAudio.setMuted(!fireAudio.muted);$('mute').textContent=fireAudio.muted?t('unmute'):t('mute');$('mute').setAttribute('aria-pressed',String(fireAudio.muted));};
$('add').onclick=()=>{const l=addLog([-.1,2.1,.1],Math.random()*Math.PI);if(l){select(l);toast('added');}};$('ignite').onclick=ignite;$('extinguish').onclick=extinguish;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?t('resume'):t('pause');};$('reset').onclick=()=>{reset();toast('cleared');};$('wind').oninput=e=>{wind=+e.target.value;$('windVal').textContent=wind.toFixed(1)+' m/s';};$('direction').oninput=e=>{direction=+e.target.value;$('dirVal').textContent=direction+'°';};$('speed').oninput=e=>{speed=+e.target.value;$('speedVal').textContent=speed+'×';};$('exposure').oninput=e=>{renderer.toneMappingExposure=T.MathUtils.clamp(Number(e.target.value),.1,2);$('exposureVal').textContent=renderer.toneMappingExposure.toFixed(2)+'×';};$('bloom').oninput=e=>{bloomPass.strength=T.MathUtils.clamp(Number(e.target.value),0,2);$('bloomVal').textContent=bloomPass.strength.toFixed(2);};$('left').onclick=()=>rotate(.18);$('right').onclick=()=>rotate(-.18);$('up').onclick=()=>raise(.18);$('down').onclick=()=>raise(-.18);$('drop').onclick=release;$('fold').onclick=()=>{$('panel').classList.toggle('collapsed');$('fold').textContent=$('panel').classList.contains('collapsed')?'+':'−';};$('hide').onclick=()=>{document.body.classList.toggle('zen');$('hide').textContent=document.body.classList.contains('zen')?t('showControls'):t('view');};
const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0),hit=new T.Vector3(),offset=new T.Vector3();let dragging=false;
function setRay(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;setRay(e);const hits=ray.intersectObjects(logs.map(l=>l.mesh));if(!hits.length){release();return;}const l=logs.find(l=>l.mesh===hits[0].object);hold(l);dragging=true;orbit.enabled=false;plane.constant=-l.body.position.y;ray.ray.intersectPlane(plane,hit);offset.copy(l.mesh.position).sub(hit);canvas.setPointerCapture(e.pointerId);e.stopImmediatePropagation();},true);
canvas.addEventListener('pointermove',e=>{if(!dragging||!held)return;setRay(e);plane.constant=-held.body.position.y;if(ray.ray.intersectPlane(plane,hit)){held.body.position.x=T.MathUtils.clamp(hit.x+offset.x,-3.5,3.5);held.body.position.z=T.MathUtils.clamp(hit.z+offset.z,-3.5,3.5);syncLog(held);}},true);
canvas.addEventListener('pointerup',()=>{if(dragging){dragging=false;release();}},true);canvas.addEventListener('pointercancel',()=>{dragging=false;release();},true);canvas.addEventListener('wheel',e=>{if(selected&&(held||e.shiftKey)){e.preventDefault();e.stopImmediatePropagation();raise(-Math.sign(e.deltaY)*.12);}}, {capture:true,passive:false});window.addEventListener('keydown',e=>{if(/INPUT|BUTTON/.test(e.target.tagName))return;if(e.code==='KeyQ')rotate(.12,e.shiftKey);if(e.code==='KeyE')rotate(-.12,e.shiftKey);if(e.code==='Escape')release();if(e.code==='ArrowUp'){e.preventDefault();raise(.12);}if(e.code==='ArrowDown'){e.preventDefault();raise(-.12);}});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);shimmer.uniforms.aspect.value=camera.aspect;depthTarget.setSize(innerWidth,innerHeight);fireUniforms.resolution.value.set(innerWidth*renderer.getPixelRatio(),innerHeight*renderer.getPixelRatio());});
const panelGuide=setupPanelUI();
if(innerWidth<700){if(!panelGuide.firstVisit){$('panel').classList.add('collapsed');$('fold').textContent='+';}camera.position.set(5.6,4.6,9);orbit.target.set(0,.7,0);}
let last=performance.now(),uiTime=0;const endA=new T.Vector3(),endB=new T.Vector3(),center=new T.Vector3();
function animate(now){requestAnimationFrame(animate);const realdt=Math.min((now-last)/1000,.05);last=now;const dt=paused?0:realdt*speed;if(dt){elapsed+=dt;const steps=Math.max(1,Math.ceil(dt/.025));for(let i=0;i<steps;i++){world.step(dt/steps);burnStep(dt/steps);}for(let l of logs)syncLog(l);}fireUniforms.windV.value.set(Math.cos(direction*Math.PI/180)*wind,Math.sin(direction*Math.PI/180)*wind);sourceData.fill(0);let power=0;for(let i=0;i<MAX;i++){const l=logs[i];if(l){endA.set(-l.length*.44,0,0).applyQuaternion(l.mesh.quaternion).add(l.mesh.position);endB.set(l.length*.44,0,0).applyQuaternion(l.mesh.quaternion).add(l.mesh.position);emitA[i].set(endA.x,endA.y,endA.z,l.burn);emitB[i].set(endB.x,endB.y,endB.z,0);sourceData.set(emitA[i].toArray(),i*8);sourceData.set(emitB[i].toArray(),i*8+4);power+=l.burn;}else{emitA[i].set(0,0,0,0);emitB[i].set(0,0,0,0);}}fireAudio.update(realdt,logs,held,paused,camera);if(dt)updateParticles(dt);fireUniforms.time.value=elapsed;fireLight.intensity=(power*11+logs.reduce((s,l)=>s+l.heatUniform.value*1.5,0))*(.92+.06*Math.sin(elapsed*13)+.04*Math.sin(elapsed*21.1));smokeMat.uniforms.firePower.value=Math.min(power,2);center.set(0,.6,0).project(camera);shimmer.uniforms.center.value.set(center.x*.5+.5,center.y*.5+.5);shimmer.uniforms.time.value=elapsed;shimmer.uniforms.strength.value=Math.min(power/3,1.5);orbit.update();camera.updateMatrixWorld();inverseVP.multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse).invert();flame.visible=false;particles.visible=false;renderer.shadowMap.autoUpdate=false;scene.overrideMaterial=depthMaterial;renderer.setRenderTarget(depthTarget);renderer.render(scene,camera);scene.overrideMaterial=null;renderer.shadowMap.autoUpdate=true;renderer.setRenderTarget(null);flame.visible=true;particles.visible=true;composer.render();uiTime+=realdt;if(uiTime>.2){updateUI();uiTime=0;}}
initI18n();window.addEventListener('ember-languagechange',updateUI);
let wakeState='wakeOff';const renderWake=()=>{$('wakeStatus').textContent=t(wakeState);};
const screenWake=setupWakeLock({onState(key){wakeState=key;renderWake();}});
$('wakeToggle').checked=false;
$('wakeToggle').addEventListener('change',e=>screenWake.setEnabled(e.target.checked));
window.addEventListener('ember-languagechange',renderWake);

try{reset();await initGPU();$('loading').remove();panelGuide.start();requestAnimationFrame(animate);}catch(e){console.error(e);$('loading').textContent=t('renderError');}
const context=document.modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'control_campfire',description:t('toolDescription'),inputSchema:{type:'object',properties:{action:{type:'string',enum:['add_log','ignite','extinguish']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!['add_log','ignite','extinguish'].includes(input.action))throw Error('Invalid action');if(input.action==='add_log')$('add').click();else if(input.action==='ignite')ignite();else extinguish();updateUI();return {logs:logs.length,burning:logs.filter(l=>l.burn>.1).length};}})).catch(console.warn);}catch(e){console.warn(e);}}
